osx_image: xcode8.3
language: objective-c
before_install:
  - pod repo update --silent
  - gem install cocoapods
  - pod install --repo-update --silent --project-directory=Example
  - instruments -s devices
  - xcodebuild -showsdks
script:
  - ./build.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)