osx_image: xcode8.1
language: objective-c
before_install:
  - pod repo update --silent
  - gem install cocoapods
  - pod install --project-directory=Example
  - instruments -s devices
  - xcodebuild -showsdks
script:
- set -o pipefail && xcodebuild -workspace Example/QminderTVApp.xcworkspace -scheme QminderTVApp -destination 'platform=tvOS Simulator,name=Apple TV 1080p' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO QMINDER_API_KEY=$QMINDER_API_KEY clean test build | xcpretty
- pod lib lint --verbose