ignore:
  - "Example"
  - "test-server"
  - "docs"
  - "Pods"
comment:
  layout: "header, reach, diff, flags, files, footer"
  behavior: default
  require_changes: no
  branches: null
  paths: null

coverage:
  notify:
    slack:
      default:
        threshold: 1%
        only_pulls: false
        branches: null
        flags: null
        paths: null
