ignore:
  - "Example"
  - "test-server"
  - "docs"
  - "Pods"
  - "QminderAPITests"
  - "Example/Pods"
  - "Sources/API.swift"
comment:
  layout: "header, reach, diff, flags, files, footer"
  behavior: new
  require_changes: true
  branches: null
  paths: null

coverage:
  notify:
    slack:
      default:
        url: "https://hooks.slack.com/services/T02BHE0G7/B9FETM8FN/SLACK_KEY"
        threshold: 1%
        only_pulls: false
        branches: null
        flags: null
        paths: null
