name: Build Swift API
on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build
    - name: Carthage
      uses: |
            brew update
            brew outdated carthage || brew upgrade carthage
            scripts/bootstrap-if-needed.sh
